language: python
python: 2.7
env:
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3 QA=true
matrix:
  include:
    - python: 2.6
      env: PLONE_VERSION=4.1
install:
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg annotate
  # workaround for failing installation under Plone 4.1
  - test -v QA && bin/buildout -c travis.cfg -N -q || bin/buildout -c travis.cfg -N -q buildout:parts-=code-analysis
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - firefox -v
script:
  - test $QA && bin/code-analysis || true
  - bin/test
after_success:
  - test $QA && bin/coverage.sh && pip install -q coveralls && coveralls || true
notifications:
  irc: irc.freenode.org#simplesconsultoria
